FROM gcc:latest
MAINTAINER Tom Denham <tom@projectcalico.org>

RUN dpkg --add-architecture arm64
RUN dpkg --add-architecture armhf
RUN dpkg --add-architecture ppc64el
RUN dpkg --add-architecture s390x
RUN dpkg --add-architecture mips64el
RUN apt update
RUN apt-get --no-install-recommends install -y autoconf flex bison \
	libncurses-dev libreadline-dev \
	binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu libncurses-dev:arm64 libreadline-dev:arm64 \
	binutils-powerpc64le-linux-gnu gcc-powerpc64le-linux-gnu libncurses-dev:ppc64el libreadline-dev:ppc64el \
	binutils-s390x-linux-gnu gcc-s390x-linux-gnu libncurses-dev:s390x libreadline-dev:s390x \
	binutils-mips64el-linux-gnuabi64 gcc-mips64el-linux-gnuabi64 libncurses-dev:mips64el libreadline-dev:mips64el \
	binutils-arm-linux-gnueabi gcc-arm-linux-gnueabihf libncurses-dev:armhf libreadline-dev:armhf

WORKDIR /code
