#!/bin/sh
exec 2>&1
exec /confd -confdir=/ -interval=5 -watch --log-level=debug \
     -node=${ETCD_SCHEME:=http}://${ETCD_AUTHORITY} \
     -client-key=${ETCD_KEY_FILE} -client-cert=${ETCD_CERT_FILE} \
     -client-ca-keys=${ETCD_CA_CERT_FILE} -scheme=${ETCD_SCHEME:=http}
